name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login ke Docker Hub menggunakan secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Install Docker Compose di runner
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    # Step 4: Build and push Docker image to Docker Hub
    - name: Build and push Docker image
      run: |
        docker build -t fiqifahrudilah/tugas_git_action-web:1.0.0 .
        docker push fiqifahrudilah/tugas_git_action-web:1.0.0

    # Step 5: Deploy to EC2 via SSH
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        # Save private key to a temporary file
        echo "$EC2_KEY" > ec2-key.pem
        chmod 600 ec2-key.pem

        # SSH into EC2 and run Docker commands
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST << EOF
          # Login to Docker Hub
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          # Pull the latest Docker image
          docker pull fiqifahrudilah/tugas_git_action-web:1.0.0
          
          # Clone the repository to get the latest docker-compose.yml
          git clone https://github.com/SoraIroShiro/tugas_git_action.git /home/ubuntu/tugas_git_action

          # Change to project directory
          cd /home/ubuntu/tugas_git_action || exit 1
          
          # Install Nginx
          sudo apt update
          sudo apt install -y nginx

          # Start Nginx service
          sudo systemctl start nginx
          sudo systemctl enable nginx

          # Ensure Nginx is running and accessible
          sudo systemctl status nginx

          # Download docker-compose.yml file from the GitHub repository
          curl -O https://raw.githubusercontent.com/SoraIroShiro/tugas_git_action/main/docker-compose.yml
          
          # Run Docker Compose
          docker-compose down || true
          docker-compose up -d
        EOF

        # Clean up private key after deployment
        rm -f ec2-key.pem
