name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: fiqifahrudillah
        password: konfirmasi123

    - name: Build and push Docker image
      run: |
        docker build -t username/static-web-nginx:latest .
        docker push username/static-web-nginx:latest

    - name: Deploy with Docker Compose
      run: |
        docker-compose down
        docker-compose up -d
