name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Login ke Docker Hub menggunakan secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Install Docker Compose di runner
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    # Step 4: Build dan push image ke Docker Hub
    - name: Build and push Docker image
      run: |
        docker build -t fiqifahrudilah/tugas_git_action-web:1.0.0 .
        docker push fiqifahrudilah/tugas_git_action-web:1.0.0

    # Step 5: Deploy ke EC2 dengan SSH
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_KEY: ${{ secrets.EC2_KEY }}
      run: |
        # Simpan private key ke file sementara
        echo "$EC2_KEY" > ec2-key.pem
        chmod 600 ec2-key.pem

        # SSH ke EC2 dan jalankan perintah Docker Compose
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST << EOF
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull fiqifahrudilah/tugas_git_action-web:1.0.0
          docker-compose down || true
          docker-compose up -d
        EOF

        # Hapus file private key setelah selesai
        rm -f ec2-key.pem
